{% set name = "graphlib-backport" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphlib_backport-{{ version }}.tar.gz
  sha256: 00a7888b21e5393064a133209cb5d3b3ef0a2096cf023914c9d778dff5644125

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --use-deprecated=out-of-tree-build

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - python >=3.6,<4.0

test:
  imports:
    - graphlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/graphlib-backport/
  summary: Backport of the Python 3.9 graphlib module for Python 3.6+
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
